# Generated by Django 5.2.3 on 2025-06-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0004_remove_project_images_remove_project_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_testimonial_author',
            field=models.CharField(blank=True, help_text='Nombre del autor del testimonio para este proyecto.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_testimonial_quote',
            field=models.TextField(blank=True, help_text='Cita del testimonio de un cliente para este proyecto específico.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servicios de la empresa que se utilizaron en este proyecto.', related_name='projects_related_to_service', to='services.service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(help_text='Categorías a las que pertenece este proyecto.', related_name='projects', to='projects.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='Nombre del cliente (opcional).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(help_text='Descripción completa y detallada del proyecto.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text="Duración del proyecto (ej. '3 meses', '2022-2023').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación del proyecto (ej. Buenos Aires, Argentina).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, help_text="Tipo de servicio (ej. 'Construcción', 'Remodelación', 'Diseño').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Breve descripción del proyecto para listados.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Slug para URLs amigables (se genera automáticamente).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Título del proyecto.', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(help_text='Nombre de la categoría (ej. Residencial, Comercial).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Leyenda o descripción de la imagen.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Archivo de imagen del proyecto.', upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_main_image',
            field=models.BooleanField(default=False, help_text='Marca si esta es la imagen principal para miniaturas o carruseles.'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(help_text='El proyecto al que pertenece esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
