# Generated by Django 5.2.3 on 2025-06-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='Sin descripción', max_length=255),
            preserve_default=False,
        ),
    ]
