# Generated by Django 5.2.3 on 2025-06-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Categoría a la que pertenece este servicio.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Descripción detallada del servicio.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del servicio.', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Breve descripción del servicio para listados o tarjetas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug para URLs amigables (se genera automáticamente).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Título del servicio.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la categoría de servicio.'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icono representativo de la categoría (opcional).', null=True, upload_to='service_icons/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(help_text='Nombre de la categoría de servicio (ej. Construcción Residencial).', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
