# Generated by Django 5.2.3 on 2025-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Quiénes Somos'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='main_content',
            field=models.TextField(help_text="Contenido principal de la sección 'Quiénes Somos' (ej. historia de la empresa)."),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(blank=True, help_text='Declaración de la misión de la empresa.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text="Miembros del equipo destacados en la sección 'Quiénes Somos'.", related_name='about_sections', to='about.teammember'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='testimonials',
            field=models.ManyToManyField(blank=True, help_text="Testimonios destacados en la sección 'Quiénes Somos'.", related_name='about_sections', to='about.testimonial'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='Quiénes Somos', help_text="Título de la sección 'Quiénes Somos' (para futuras traducciones o variaciones).", max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='values',
            field=models.ManyToManyField(blank=True, help_text="Valores asociados a la sección 'Quiénes Somos'.", related_name='about_sections', to='about.value'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.TextField(blank=True, help_text='Declaración de la visión de la empresa.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve biografía o descripción del miembro.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del miembro del equipo.', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(help_text='Cargo o posición del miembro del equipo (ej. Arquitecto, Fundador).', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(help_text='Nombre del cliente que da el testimonio.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(help_text='Contenido del testimonio.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del cliente (opcional).', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(help_text='Descripción detallada del valor.'),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icono que representa el valor.', null=True, upload_to='values/'),
        ),
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(help_text='Nombre del valor (ej. Innovación, Compromiso).', max_length=255, unique=True),
        ),
    ]
