# Generated by Django 5.2.3 on 2025-07-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría del proveedor.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Proveedor',
                'verbose_name_plural': 'Categorías de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proveedor.', max_length=255)),
                ('logo', models.ImageField(help_text='Logo del proveedor. Idealmente cuadrado o con fondo transparente.', upload_to='proveedores_logos/')),
                ('website', models.URLField(blank=True, help_text='Sitio web del proveedor (opcional).', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Breve descripción de lo que provee o su relación con la empresa (opcional).', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar si este proveedor debe aparecer en la página de inicio.')),
                ('category', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece el proveedor (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='proveedores.proveedorcategory')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
